export const FETCH_TUTELAS_SUCCESS = 'FETCH_TUTELAS_SUCCESS';
export const FETCH_TUTELA_SUCCESS = 'FETCH_TUTELA_SUCCESS';
export const CREATE_TUTELA_SUCCESS = 'CREATE_TUTELA_SUCCESS';
export const UPDATE_TUTELA_SUCCESS = 'UPDATE_TUTELA_SUCCESS';
export const DELETE_TUTELA_SUCCESS = 'DELETE_TUTELA_SUCCESS';
export const SET_USER_ID = 'SET_USER_ID';